---
abstract: 'A tool to grab GNU softwares'
author:
  - 'Sandro Cazzaniga <kharec@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
distribution_type: module
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.57_05'
license: GPLv3+
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: bin/gnuget
no_index:
  directory:
    - t
    - inc
requires:
  ExtUtils::MakeMaker: 0
  Net::FTP: 0
  Test::More: 0
version: 1.9
